"""initial

Revision ID: a8fe4146408a
Revises: 
Create Date: 2026-05-28 20:52:09.068823+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a8fe4146408a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Применяет миграцию: создаёт/изменяет таблицы."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('login', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index('ix_users_login', 'users', ['login'], unique=False)
    op.create_table('spheres',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('satisfaction', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spheres_created_at'), 'spheres', ['created_at'], unique=False)
    op.create_index(op.f('ix_spheres_id'), 'spheres', ['id'], unique=False)
    op.create_index(op.f('ix_spheres_user_id'), 'spheres', ['user_id'], unique=False)
    op.create_index('ix_spheres_user_id_code', 'spheres', ['user_id', 'code'], unique=True)
    op.create_table('sphere_satisfaction_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('sphere_id', sa.Uuid(), nullable=False),
    sa.Column('satisfaction', sa.Float(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sphere_id'], ['spheres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sphere_satisfaction_history_created_at'), 'sphere_satisfaction_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_sphere_satisfaction_history_id'), 'sphere_satisfaction_history', ['id'], unique=False)
    op.create_index(op.f('ix_sphere_satisfaction_history_sphere_id'), 'sphere_satisfaction_history', ['sphere_id'], unique=False)
    op.create_index(op.f('ix_sphere_satisfaction_history_user_id'), 'sphere_satisfaction_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откатывает миграцию: удаляет/возвращает таблицы к предыдущему состоянию."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sphere_satisfaction_history_user_id'), table_name='sphere_satisfaction_history')
    op.drop_index(op.f('ix_sphere_satisfaction_history_sphere_id'), table_name='sphere_satisfaction_history')
    op.drop_index(op.f('ix_sphere_satisfaction_history_id'), table_name='sphere_satisfaction_history')
    op.drop_index(op.f('ix_sphere_satisfaction_history_created_at'), table_name='sphere_satisfaction_history')
    op.drop_table('sphere_satisfaction_history')
    op.drop_index('ix_spheres_user_id_code', table_name='spheres')
    op.drop_index(op.f('ix_spheres_user_id'), table_name='spheres')
    op.drop_index(op.f('ix_spheres_id'), table_name='spheres')
    op.drop_index(op.f('ix_spheres_created_at'), table_name='spheres')
    op.drop_table('spheres')
    op.drop_index('ix_users_login', table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
