"""create

Revision ID: 00f8bf1376ef
Revises: abcdef789012
Create Date: 2026-06-27 20:16:28.646138+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00f8bf1376ef'
down_revision: Union[str, None] = 'abcdef789012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Применяет миграцию: создаёт/изменяет таблицы."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('someday_maybe',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('sphere_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sphere_id'], ['spheres.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_someday_maybe_created_at'), 'someday_maybe', ['created_at'], unique=False)
    op.create_index(op.f('ix_someday_maybe_id'), 'someday_maybe', ['id'], unique=False)
    op.create_index(op.f('ix_someday_maybe_sphere_id'), 'someday_maybe', ['sphere_id'], unique=False)
    op.create_index(op.f('ix_someday_maybe_user_id'), 'someday_maybe', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откатывает миграцию: удаляет/возвращает таблицы к предыдущему состоянию."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_someday_maybe_user_id'), table_name='someday_maybe')
    op.drop_index(op.f('ix_someday_maybe_sphere_id'), table_name='someday_maybe')
    op.drop_index(op.f('ix_someday_maybe_id'), table_name='someday_maybe')
    op.drop_index(op.f('ix_someday_maybe_created_at'), table_name='someday_maybe')
    op.drop_table('someday_maybe')
    # ### end Alembic commands ###
