"""create user_settings table

Revision ID: 63e6022f5c68
Revises: xxxxxxxxxxxx
Create Date: 2026-06-27 08:49:56.825495+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '63e6022f5c68'
down_revision: Union[str, None] = 'xxxxxxxxxxxx'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Применяет миграцию: создаёт/изменяет таблицы."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('w_proactive', sa.Float(), nullable=False),
    sa.Column('w_importance', sa.Float(), nullable=False),
    sa.Column('w_consequences', sa.Float(), nullable=False),
    sa.Column('w_urgency', sa.Float(), nullable=False),
    sa.Column('w_refusals', sa.Float(), nullable=False),
    sa.Column('w_project_speed', sa.Float(), nullable=False),
    sa.Column('w_sphere_satisfaction', sa.Float(), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), nullable=False),
    sa.Column('deadline_near', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_created_at'), 'user_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откатывает миграцию: удаляет/возвращает таблицы к предыдущему состоянию."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_created_at'), table_name='user_settings')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
