"""add sphere model

Revision ID: d85af4441a8a
Revises: 279450ea3630
Create Date: 2026-05-03 14:27:45.281218+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd85af4441a8a'
down_revision: Union[str, None] = '279450ea3630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spheres',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('satisfaction', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spheres_created_at'), 'spheres', ['created_at'], unique=False)
    op.create_index(op.f('ix_spheres_id'), 'spheres', ['id'], unique=False)
    op.create_index('ix_spheres_is_active', 'spheres', ['is_active'], unique=False)
    op.create_index(op.f('ix_spheres_user_id'), 'spheres', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spheres_user_id'), table_name='spheres')
    op.drop_index('ix_spheres_is_active', table_name='spheres')
    op.drop_index(op.f('ix_spheres_id'), table_name='spheres')
    op.drop_index(op.f('ix_spheres_created_at'), table_name='spheres')
    op.drop_table('spheres')
    # ### end Alembic commands ###
