"""add is_focused to spheres

Revision ID: 45fa311ff7d5
Revises: 00f8bf1376ef
Create Date: 2026-07-24 21:20:22.354609+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '45fa311ff7d5'
down_revision: Union[str, None] = '00f8bf1376ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Применяет миграцию: создаёт/изменяет таблицы."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spheres', sa.Column('is_focused', sa.Boolean(), nullable=False, server_default=sa.text('TRUE')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откатывает миграцию: удаляет/возвращает таблицы к предыдущему состоянию."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spheres', 'is_focused')
    # ### end Alembic commands ###


