"""create project table

Revision ID: 8459614464b5
Revises: 63e6022f5c68
Create Date: 2026-06-27 10:16:59.166361+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8459614464b5'
down_revision: Union[str, None] = '63e6022f5c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Применяет миграцию: создаёт/изменяет таблицы."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_statuses',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_statuses_code'), 'project_statuses', ['code'], unique=True)
    # Seed: статусы проекта (1-активен, 2-завершён, 3-отменён)
    op.execute("""
        INSERT INTO project_statuses (id, code, name, sort_order, color) VALUES
        (1, 'active',    'Активен',   1, '#22c55e'),
        (2, 'completed', 'Завершён',  2, '#3b82f6'),
        (3, 'cancelled', 'Отменён',   3, '#ef4444')
    """)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('sphere_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finish_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['sphere_id'], ['spheres.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['project_statuses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_projects_goal_id'), 'projects', ['goal_id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_sphere_id'), 'projects', ['sphere_id'], unique=False)
    op.create_index(op.f('ix_projects_status_id'), 'projects', ['status_id'], unique=False)
    op.create_index('ix_projects_user_goal', 'projects', ['user_id', 'goal_id'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_index('ix_projects_user_sphere', 'projects', ['user_id', 'sphere_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откатывает миграцию: удаляет/возвращает таблицы к предыдущему состоянию."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_projects_user_sphere', table_name='projects')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index('ix_projects_user_goal', table_name='projects')
    op.drop_index(op.f('ix_projects_status_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_sphere_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_goal_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_project_statuses_code'), table_name='project_statuses')
    op.drop_table('project_statuses')
    # ### end Alembic commands ###

